### ISSUE TITLE
Trackpad Gestures

### ISSUE THREAD

**Issue by mrwiwi** [apollohackintosh/Dell-5310-Hackintosh#1]
Hi ! I have the same model and started my own EFI building, i have issues with sleep and trackpad mostly, do you ?
VoodooPS2 alone doesn't give gestures here :/

**Comment by apollohackintosh** [comment]
> Hi ! I have the same model and started my own EFI building, i have issues with sleep and trackpad mostly, do you ? VoodooPS2 alone doesn't give gestures here :/

Just fixed the trackpad issues, will upload the latest EFI and sleep wake works perfectly unless you tell me otherwise but it is working on my machine. Will put the list of working items on the main page as well.

**Comment by apollohackintosh** [comment]
> Hi ! I have the same model and started my own EFI building, i have issues with sleep and trackpad mostly, do you ? VoodooPS2 alone doesn't give gestures here :/

Uploaded now, enjoy and let me know what issues you face. Still have 4 items to iron out so WIP.
